version: "3"

services:
  # The Application
  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./
      dockerfile: sourcefiles/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      - "MAIL_FROM_NAME=${MAIL_FROM_NAME}"
      - "MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}"

  # The Web Server
  web:
    container_name: ${APP_NAME}-webserver
    build:
      context: ./
      dockerfile: sourcefiles/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./src/storage/logs/:/var/log/nginx
      - ./src/storage/app:/var/www/storage/app

  # The Database
  database:
    container_name: ${APP_NAME}-database
    image: postgres:9.6
    volumes:
      - /tmp/postgresql:/data
    ports:
      - "5431:5432"
